use DBFilm
go
--taoj cho db loaiphim
insert into TB_LOAIPHIM(TENLOAIPHIM) values(N'Phim Hoạt Hình')
insert into TB_LOAIPHIM(TENLOAIPHIM) values(N'Action')
insert into TB_LOAIPHIM(TENLOAIPHIM) values(N'Drama')
insert into TB_LOAIPHIM(TENLOAIPHIM) values(N'Adventure')
insert into TB_LOAIPHIM(TENLOAIPHIM) values(N'magic')
insert into TB_LOAIPHIM(TENLOAIPHIM) values(N'horror')
insert into TB_LOAIPHIM(TENLOAIPHIM) values(N'romantic')
go
-- tạo cho db phim
insert into TB_PHIM(QUOCGIA,HINHANH,MOTAPHIM,THOILUONG,TENPHIM) values(N'Nhật Bản',N'Doremon.jpg',N'Hay',N'120',N'Nobita Và Đảo Giấu Vàng')
insert into TB_PHIM(QUOCGIA,HINHANH,MOTAPHIM,THOILUONG,TENPHIM) values(N'Mỹ',N'Endgame.jpg',N'hay',N'120',N'Avengers: Hồi kết')
insert into TB_PHIM(QUOCGIA,HINHANH,MOTAPHIM,THOILUONG,TENPHIM) values(N'Mỹ',N'shawahank.jpg',N'hay',N'120',N'Nhà tù Shawshank')
insert into TB_PHIM(QUOCGIA,HINHANH,MOTAPHIM,THOILUONG,TENPHIM) values(N'Mỹ',N'bogia.jpg',N'hay',N'120',N'Bố già')
insert into TB_PHIM(QUOCGIA,HINHANH,MOTAPHIM,THOILUONG,TENPHIM) values(N'Mỹ',N'batman.jpg',N'hay',N'120',N'Kỵ sĩ bóng đêm')
insert into TB_PHIM(QUOCGIA,HINHANH,MOTAPHIM,THOILUONG,TENPHIM) values(N'Mỹ',N'king.jpg',N'hay',N'120',N'Sự trở lại của nhà vua')
insert into TB_PHIM(QUOCGIA,HINHANH,MOTAPHIM,THOILUONG,TENPHIM) values(N'Mỹ',N'Inception.jpg',N'hay',N'120',N' Kẻ đánh cắp giấc mơ')
insert into TB_PHIM(QUOCGIA,HINHANH,MOTAPHIM,THOILUONG,TENPHIM) values(N'Mỹ',N'The_Conjuring.jpg',N'hay',N'120',N'The Conjuring')
insert into TB_PHIM(QUOCGIA,HINHANH,MOTAPHIM,THOILUONG,TENPHIM) values(N'Mỹ',N'Get_out.jpg',N'hay',N'120',N'Get out')
insert into TB_PHIM(QUOCGIA,HINHANH,MOTAPHIM,THOILUONG,TENPHIM) values(N'Mỹ',N'IT.jpg',N'hay',N'120',N'IT')
insert into TB_PHIM(QUOCGIA,HINHANH,MOTAPHIM,THOILUONG,TENPHIM) values(N'Anh',N'The_Shining.jpg',N'hay',N'120',N'The Shining')
insert into TB_PHIM(QUOCGIA,HINHANH,MOTAPHIM,THOILUONG,TENPHIM) values(N'Mỹ',N'Hereditary.jpg',N'hay',N'120',N'Hereditary')
insert into TB_PHIM(QUOCGIA,HINHANH,MOTAPHIM,THOILUONG,TENPHIM) values(N'Mỹ',N'Inside_Out.jpg',N'hay',N'120',N'Inside Out')
insert into TB_PHIM(QUOCGIA,HINHANH,MOTAPHIM,THOILUONG,TENPHIM) values(N'Nhật Bản',N'Totoro.jpg',N'hay',N'120',N'My Neighbor Totoro')
insert into TB_PHIM(QUOCGIA,HINHANH,MOTAPHIM,THOILUONG,TENPHIM) values(N'Nhật Bản',N'Howl.jpg',N'hay',N'120',N'Howl Moving Castle')
insert into TB_PHIM(QUOCGIA,HINHANH,MOTAPHIM,THOILUONG,TENPHIM) values(N'Mỹ',N'Up.jpg',N'hay',N'120',N'Up')
insert into TB_PHIM(QUOCGIA,HINHANH,MOTAPHIM,THOILUONG,TENPHIM) values(N'Tây Ban Nha',N'Klaus.jpg',N'hay',N'120',N'Klaus')
insert into TB_PHIM(QUOCGIA,HINHANH,MOTAPHIM,THOILUONG,TENPHIM) values(N'Nhật Bản',N'A_Silent_Voice.jpg',N'hay',N'120',N'A Silent Voice ')
insert into TB_PHIM(QUOCGIA,HINHANH,MOTAPHIM,THOILUONG,TENPHIM) values(N'Nhật Bản',N'Princess_Mononoke.jpg',N'hay',N'120',N'Princess Mononoke')
insert into TB_PHIM(QUOCGIA,HINHANH,MOTAPHIM,THOILUONG,TENPHIM) values(N'Nhật Bản',N'Your_name.jpg',N'hay',N'120',N'Your name')
go
--tạo db cho bảng trung gian phim
insert into TB_Phim_LoaiPhim values(N'1',N'1')
insert into TB_Phim_LoaiPhim values(N'2',N'2')
insert into TB_Phim_LoaiPhim values(N'2',N'3')
insert into TB_Phim_LoaiPhim values(N'2',N'4')
insert into TB_Phim_LoaiPhim values(N'13',N'1')
insert into TB_Phim_LoaiPhim values(N'14',N'1')
insert into TB_Phim_LoaiPhim values(N'15',N'1')
insert into TB_Phim_LoaiPhim values(N'16',N'1')
insert into TB_Phim_LoaiPhim values(N'17',N'1')
insert into TB_Phim_LoaiPhim values(N'18',N'1')
insert into TB_Phim_LoaiPhim values(N'19',N'1')
insert into TB_Phim_LoaiPhim values(N'20',N'1')
insert into TB_Phim_LoaiPhim values(N'8',N'6')
insert into TB_Phim_LoaiPhim values(N'9',N'6')
insert into TB_Phim_LoaiPhim values(N'10',N'6')
insert into TB_Phim_LoaiPhim values(N'11',N'6')
insert into TB_Phim_LoaiPhim values(N'12',N'6')
insert into TB_Phim_LoaiPhim values(N'3',N'2')
insert into TB_Phim_LoaiPhim values(N'3',N'3')
insert into TB_Phim_LoaiPhim values(N'4',N'2')
insert into TB_Phim_LoaiPhim values(N'5',N'2')
insert into TB_Phim_LoaiPhim values(N'5',N'3')
insert into TB_Phim_LoaiPhim values(N'5',N'4')
insert into TB_Phim_LoaiPhim values(N'6',N'2')
insert into TB_Phim_LoaiPhim values(N'6',N'3')
insert into TB_Phim_LoaiPhim values(N'6',N'4')
insert into TB_Phim_LoaiPhim values(N'7',N'2')
insert into TB_Phim_LoaiPhim values(N'7',N'3')
insert into TB_Phim_LoaiPhim values(N'7',N'4')
